export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const GET_ALL_WATCHLIST = 'GET_ALL_WATCHLIST';
export const SET_WATCHLIST = 'SET_WATCHLIST';
