export default {
    common: {
        defaultLanguage: 'English',
        close: 'Close',
        noText: 'No text',
        noData: 'No Data',
        cancel: 'Cancel',
        confirm: 'Confirm',
        haveAnAcc: 'Do you have an account? ',
        login: 'Login',
        stockMarket: 'Stock Market',
        open: 'Open',
        high: 'High',
        low: 'Low',
        stock: 'Stock market',
        change1: 'Change: ',
        closeStock: 'Close',
        volume: 'Traded Volume',
        date: 'Date',
        symbol: 'Symbol',
        open1: 'Open: ',
        high1: 'High: ',
        low1: 'Low: ',
        stock1: 'Stock market: ',
        closeStock1: 'Close: ',
        volume1: 'Traded Volume: ',
        date1: 'Date: ',
        symbol1: 'Symbol: ',
        search: 'Search',
        notFound: 'Not found',
        ok: 'OK',
        setting: 'Setting',
        update: 'Updated At {{value}}',
        newPass: 'Set new password',
        loading: 'Loading',
        graph: 'Stock chart closing price',
        guide: 'Guide',
        real: ' Reality',
        predict: ' Prediction',
    },
    forgotPass: {
        title: 'Forgot Password',
        subTitle: 'Please enter your email we will resend you a verify code.',
        next: 'Next',
    },
    aboutUs: {
        title: 'About us',
    },
    detailStock: {
        title: 'Stock Detail',
    },
    term: {
        title: 'Term and services',
        requireAge: 'Age requirements',
        contentAge:
            'If you’re under the age required to manage your own account, you must have your parent or legal guardian’s permission to use a account. Please have your parent or legal guardian read these terms with you.',
        requireRespect: 'Respect others',
        contentRes:
            'Don’t abuse, harm, interfere with, or disrupt the services — for example, by accessing or using them in fraudulent or deceptive ways, introducing malware, or spamming, hacking, or bypassing our systems or protective measures',
        requireRule: 'Permission to use your content',
        contentRule:
            'Some of our services are designed to let you upload, submit, store, send, receive, or share your content. You have no obligation to provide any content to our services and you’re free to choose the content that you want to provide. If you choose to upload or share content, please make sure you have the necessary rights to do so and that the content is lawful.',
    },
    privacy: {
        title: 'Privacy Policy',
        subTitle: 'Stock Market Privacy Policy',
        content:
            'When you use our services, you’re trusting us with your information. We understand this is a big responsibility and work hard to protect your information and put you in control.',
        subContent:
            'This Privacy Policy is meant to help you understand what information we collect, why we collect it, and how you can update, manage, export, and delete your information.',
    },
    permissions: {
        camera: 'Stock Market need the camera permission',
        photo: 'Stock Market need access library permission',
    },
    stock: {
        highestVolume: 'Highest trading volume today',
        stockToday: 'Stock Market Data',
    },
    news: {
        comment: 'Comment',
        addNews: 'Post something...',
        hide: 'This post has been hidden',
        hideComment: 'Comment was hidden',
    },
    addNews: {
        title: 'Title',
        content: 'Content',
        takePictureHeader: 'Take a photo',
        takePicture: 'Camera',
        chooseFromAlbum: 'Library',
        upload: 'Post',
        noComment: 'No comments yet',
    },
    watchlist: {
        noData: 'You do not have any symbol in watch list',
        title: 'Watch List',
    },
    courseScreen: {
        all: 'All',
        noCourse: 'No courses yet',
        author: 'Author {{ value }}',
        createdAt: 'Created at {{ value }}',
    },
    firstScreen: {
        brand: 'STOCK MARKET',
        description: 'Feel the new \n experience of my product',
        gettingStarted: 'Getting Started',
    },
    modalInput: {
        title: 'Hello',
        close: 'Close',
        button: 'displayModal1',
    },
    tab: {
        home: 'Home',
        news: 'News',
        market: 'Watchlist',
        setting: 'Settings',
        course: 'Course',
    },
    alert: {
        button: {
            no: 'No',
            yes: 'Yes',
        },
        addSuccess: 'Add success!',
        updateSuccess: 'Update success',
        warning: 'Warning',
    },
    loginScreen: {
        buttonLogin: 'Login',
        labelEmail: 'Email',
        labelPassword: 'Password',
        forgotPassword: 'Forgot password?',
        dontHaveAnAccount: 'You do not have an account? ',
        register: 'Register',
    },
    registerScreen: {
        title: 'Register',
        username: 'Username',
        phone: 'Phone',
        email: 'Email',
        password: 'Password',
        confirm_password: 'Confirm password',
        placeholder_username: 'Tuan Pham Ngoc',
        haveAnAccount: 'Do you have an account? ',
        login: 'Login',
        photo: 'Album',
        camera: 'Take a photo',
        selectPhoto: 'Camera',
        chooseImage: 'Library',
    },
    validateMessage: {
        nameRequired: 'At least 6 character of username',
        signIn: 'Password is incorrect!',
        infoInvalid: 'Info invalid!',
        notCompleted: 'You have not entered the information.',
        emailNotRegister: 'Please enter your email!',
        validatePassword: 'At least 6 character of password!',
        minLength: 'At least 6 character of password!',
        emailInvalid: 'Email is not in the correct format!',
        passwordLength: 'At least 6 character of password!',
        confirmPasswordLength: 'The password and confirmation password do not match.',
        passwordNotMatch: 'The password and confirmation password do not match.',
        emailEmpty: 'Please enter your email!',
        messageLength: 'Do not enter more than 1000 characters.',
        success: 'Register success!',
        titleRequired: 'Title is required!',
        contentRequired: 'Content is required!',
        phoneInvalid: 'Phone invalid',
        require: 'Please enter the information',
        notMatchPassword: 'The password and confirmation password do not match.',
    },
    sendOTP: {
        title: 'Email Verification',
        subTitle: 'Please check your email.',
        success: 'A new verification code has been sent.',
        invalidOTP: 'The authorization code is incorrect.',
        resend: 'Resend',
        buttonNext: 'Next',
    },
    input: {
        errorComponent: 'You need wrap input by Form Provider or passing "form = useForm( ... )" into input component',
    },
    settings: {
        logout: 'Logout',
        profile: 'Update Profile',
        english: 'English',
        changeLang: 'Change language',
        selectLang: 'Language selection',
        multiLangSupported: 'Multi language supported',
        vietnamese: 'Vietnamese',
        deleteAccount: 'Delete account',
        delete: 'Confirm',
        deleteConfirm: 'Do you want to delete your account?',
        changePass: 'Change password',
        aboutUs: 'About Us',
        privacyPolicy: 'Privacy policy',
        termsOfService: 'Terms of service',
    },
    updateProfile: {
        update: 'Update',
        reset: 'Reset',
    },
    confirmModal: {
        addToWatchlist: 'Add stock to watch list',
        contentTextAdd: 'Easy to follow your watch list',
        remove: 'Remove stock from watch list',
        delete: 'Are you sure to delete your post',
    },
    changePass: {
        oldPass: 'Old password',
        newPass: 'New password',
        confirmPass: 'Confirm password',
    },
    toastMessage: {
        addSuccess: 'Add symbol to watch list successfully',
        removeSuccess: 'Remove symbol from watch list successfully',
        deleteSuccess: 'Delete successfully',
        addPostSuccess: 'Post successfully',
        updatePostSuccess: 'Update post successfully',
        nothingToComment: 'Please write your comment',
        commentSuccess: 'Comment successfully!',
        updateProfileSuccess: 'Update profile successfully',
        changeSuccess: 'Change password successfully!',
    },
};
