export default {
    common: {
        defaultLanguage: 'English',
        close: 'Đóng',
        noText: 'Không có',
        noData: 'Không có dữ liệu',
        cancel: 'Huỷ bỏ',
        confirm: 'Xác nhận',
        haveAnAcc: 'Bạn có tài khoản? ',
        login: 'Đăng Nhập',
        stockMarket: 'Stock Market',
        open: 'Giá mở phiên',
        high: 'Giá cao nhất',
        low: 'Giá thấp nhất',
        closeStock: 'Giá đóng phiên',
        volume: 'Số giao dịch',
        stock: 'Thị trường chứng khoán',
        date: 'Ngày',
        symbol: 'Mã chứng khoán',
        open1: 'Giá mở phiên: ',
        high1: 'Giá cao nhất: ',
        low1: 'Giá thấp nhất: ',
        closeStock1: 'Giá đóng phiên: ',
        volume1: 'Số giao dịch: ',
        stock1: 'Thị trường chứng khoán: ',
        date1: 'Ngày: ',
        symbol1: 'Mã chứng khoán: ',
        change: 'Thay đổi',
        change1: 'Thay đổi: ',
        search: 'Tìm kiếm',
        notFound: 'Không tìm thấy!',
        ok: 'Đồng ý',
        setting: 'Cài đặt',
        update: 'Cập nhật {{value}}',
        newPass: 'Đặt lại mật khẩu mới',
        loading: 'Đang tải',
        graph: 'Biểu đồ cập nhật giá đóng phiên',
        guide: 'Chú thích',
        real: ' Thực tế',
        predict: ' Dự đoán',
    },
    forgotPass: {
        title: 'Quên mật khẩu',
        subTitle: 'Vui lòng nhập email bạn đã đăng ký, chúng tôi sẽ gửi bạn một mã xác thực.',
        next: 'Tiếp theo',
    },
    aboutUs: {
        title: 'Về chúng tôi',
    },
    detailStock: {
        title: 'Chi tiết',
    },
    term: {
        title: 'Điều khoản dịch vụ',
        requireAge: 'Yêu cầu về độ tuổi',
        contentAge:
            'Nếu bạn chưa đủ tuổi để quản lý Tài khoản của riêng mình , bạn phải được cha mẹ hoặc người giám hộ hợp pháp cho phép sử dụng Tài khoản. Vui lòng yêu cầu cha mẹ hoặc người giám hộ hợp pháp của bạn đọc các điều khoản này với bạn. Nếu bạn là cha mẹ hoặc người giám hộ hợp pháp và bạn cho phép con mình sử dụng các dịch vụ , thì các điều khoản này sẽ áp dụng cho bạn và bạn chịu trách nhiệm về hoạt động của con mình trên các dịch vụ.',
        requireRespect: 'Tôn trọng người khác',
        contentRes:
            'Không lạm dụng, gây hại, can thiệp hoặc làm gián đoạn các dịch vụ - ví dụ: bằng cách truy cập hoặc sử dụng chúng theo những cách gian lận hoặc lừa đảo, đưa phần mềm độc hại vào hoặc gửi thư rác, tấn công hoặc bỏ qua hệ thống hoặc các biện pháp bảo vệ của chúng tôi.',
        requireRule: 'Quyền sử dụng nội dung của bạn',
        contentRule:
            'Một số dịch vụ của chúng tôi được thiết kế để cho phép bạn tải lên, gửi, lưu trữ, gửi, nhận hoặc chia sẻ nội dung của mình . Bạn không có nghĩa vụ phải cung cấp bất kỳ nội dung nào cho các dịch vụ của chúng tôi và bạn có thể tự do lựa chọn nội dung mà mình muốn cung cấp. Nếu bạn chọn tải lên hoặc chia sẻ nội dung, hãy đảm bảo rằng bạn có các quyền cần thiết để làm như vậy và nội dung đó là hợp pháp.',
    },
    privacy: {
        title: 'Chính sách bảo mật',
        subTitle: 'Chính sách bảo mật của Stock Market',
        content:
            'Khi bạn sử dụng dịch vụ của chúng tôi, bạn đang tin tưởng chúng tôi cung cấp thông tin của bạn. Chúng tôi hiểu đây là một trách nhiệm lớn và làm việc chăm chỉ để bảo vệ thông tin của bạn và giúp bạn kiểm soát.',
        subContent:
            'Chính sách Bảo mật này nhằm giúp bạn hiểu thông tin nào chúng tôi thu thập, lý do chúng tôi thu thập thông tin đó và cách bạn có thể cập nhật, quản lý, xuất và xóa thông tin của mình.',
    },
    permissions: {
        camera: 'Stock Market cần quyền truy cập Camera.',
        photo: 'Stock Market cần quyền truy cập thư viện.',
    },
    stock: {
        highestVolume: 'Top giao dịch trong ngày',
        stockToday: 'Thị trường chứng khoán hôm nay',
    },
    news: {
        comment: 'Bình luận',
        addNews: 'Viết điều gì đó...',
        hide: 'Bài viết này đã bị ẩn',
        noComment: 'Chưa có bình luận nào',
        hideComment: 'Bình luận bị ẩn',
    },
    addNews: {
        title: 'Tiêu đề ',
        content: 'Nội dung',
        takePictureHeader: 'Chụp ảnh hoặc chọn từ thư viện.',
        takePicture: 'Máy ảnh',
        chooseFromAlbum: 'Thư viện',
        upload: 'Đăng bài',
    },
    watchlist: {
        noData: 'Bạn chưa thêm mã nào trong danh sách theo dõi',
        title: 'Danh sách theo dõi',
    },
    courseScreen: {
        all: 'Tất cả',
        noCourse: 'Không có khoá học nào',
        author: 'Tác giả {{ value }}',
        createdAt: 'Ngày {{ value }}',
    },
    firstScreen: {
        brand: 'STOCK MARKET',
        description: 'Trải nghiệm mới mẻ \n cùng với sản phẩm của chúng tôi',
        gettingStarted: 'Bắt đầu',
    },
    modalInput: {
        title: 'Xin chào',
        close: 'Đóng',
        button: 'displayModal1',
    },
    tab: {
        home: 'Trang chủ',
        news: 'Bảng tin',
        market: 'Thị trường',
        setting: 'Cài đặt',
        course: 'Khoá học',
    },
    alert: {
        button: {
            no: 'Không',
            yes: 'Đồng ý',
        },
        addSuccess: 'Thêm thành công!',
        updateSuccess: 'Cập nhật thành công',
        warning: 'Cảnh báo!',
    },
    noData: {
        noDataList: 'Không có dữ liệu',
    },
    loginScreen: {
        buttonLogin: 'Đăng nhập',
        labelEmail: 'Email',
        labelPassword: 'Mật khẩu',
        forgotPassword: 'Quên mật khẩu?',
        dontHaveAnAccount: 'Bạn không có tài khoản? ',
        register: 'Đăng ký',
    },
    registerScreen: {
        title: 'Đăng ký',
        username: 'Tên đăng nhập',
        phone: 'Số điện thoại',
        email: 'Email',
        password: 'Mật khẩu',
        confirm_password: 'Xác nhận mật khẩu',
        placeholder_username: 'Tuan Pham Ngoc',
        haveAnAccount: 'Bạn đã có tài khoản? ',
        login: 'Đăng nhập',
        photo: 'Thư viện',
        camera: 'Camera',
        selectPhoto: 'Chọn ảnh',
        chooseImage: 'Chọn một bức ảnh',
    },
    validateMessage: {
        nameRequired: 'Tên đăng nhập phải trên 6 ký tự',
        signIn: 'Mật khẩu không chính xác!',
        infoInvalid: 'Thông tin sai!',
        notCompleted: 'Xin hãy điền tất cả!',
        emailNotRegister: 'Địa chỉ email chưa được đăng ký!',
        validatePassword: 'Mật khẩu phải có ít nhất 6 ký tự!',
        emailInvalid: 'Địa chỉ email sai.',
        passwordLength: 'Mật khẩu phải có ít nhất 6 ký tự!',
        confirmPasswordLength: 'Mật khẩu xác nhận sai!',
        passwordNotMatch: 'Mật khẩu xác nhận chưa trùng khớp.',
        emailEmpty: 'Không được để trống email.',
        notMatchPassword: 'Mật khẩu không trùng khớp',
        messageLength: 'Hãy soạn thảo từ 30 ký tự trở lên!',
        success: 'Đăng ký thành công!',
        titleRequired: 'Tiêu đề là bắt buộc!',
        contentRequired: 'Nội dung là bắt buộc',
        minLength: 'Mật khẩu phải có ít nhất 6 ký tự!',
        phoneInvalid: 'Số điện thoại không khả dụng',
        require: 'Xin vui lòng nhập thông tin.',
    },
    sendOTP: {
        title: 'Xác thực Email',
        subTitle: 'Vui lòng kiểm tra email của bạn.',
        success: 'Tôi đã gửi cho bạn một mã mới',
        invalidOTP: 'Mã bạn nhập không chính xác',
        resend: 'Gửi lại',
        buttonNext: 'Tiếp theo',
    },
    input: {
        errorComponent: 'You need wrap input by Form Provider or passing "form = useForm( ... )" into input component',
    },
    settings: {
        logout: 'Đăng xuất',
        profile: 'Cập nhật tài khoản',
        english: 'Tiếng Anh',
        vietnamese: 'Tiếng Việt',
        changeLang: 'Thay đổi ngôn ngữ',
        selectLang: 'Lựa chọn ngôn ngữ',
        multiLangSupported: 'Được hỗ trợ tiếng anh và tiếng việt.',
        delete: 'Xác nhận',
        deleteAccount: 'Xoá tài khoản',
        deleteConfirm: 'Bạn muốn xoá tài khoản?',
        changePass: 'Thay đổi mật khẩu',
        privacyPolicy: 'Chính sách bảo mật',
        termsOfService: 'Điều khoản dịch vụ',
        aboutUs: 'Về chúng tôi',
    },
    updateProfile: {
        update: 'Cập nhật',
        reset: 'Huỷ thay đổi',
    },
    changePass: {
        oldPass: 'Mật khẩu cũ',
        newPass: 'Mật khẩu mới',
        confirmPass: 'Xác nhận mật khẩu',
    },
    confirmModal: {
        addToWatchlist: 'Thêm vào danh sách theo dõi',
        contentTextAdd: 'Dễ dàng theo dõi mã chứng khoán mà bạn quan tâm',
        remove: 'Xoá khỏi danh sách theo dõi',
        delete: 'Bạn muốn xoá bài đăng này?',
    },
    toastMessage: {
        addSuccess: 'Thêm thành công vào danh sách theo dõi!',
        removeSuccess: 'Xoá thành công khỏi danh sách theo dõi!',
        deleteSuccess: 'Xoá thành công!',
        addPostSuccess: 'Đăng bài thành công!',
        updatePostSuccess: 'Cập nhật bài thành công!',
        nothingToComment: 'Bạn chưa viết bình luận trước khi gửi',
        commentSuccess: 'Đã đăng bình luận của bạn',
        updateProfileSuccess: 'Chỉnh sửa thông tin thành công!',
        changeSuccess: 'Đổi mật khẩu thành công!',
    },
};
